[package]
name = "iterum"
version = "0.0.1"
edition = "2024"

[profile.dev]
opt-level = 1
debug = true
incremental = true
codegen-units = 256

[profile.dev.package."*"]
opt-level = 3

[profile.release]
opt-level = 3
panic = "abort"
strip = true
lto = "fat"
codegen-units = 1
debug = false
overflow-checks = false
rpath = false

[profile.release.package."*"]
opt-level = 3

[build-dependencies]
csbindgen = "1"

[dependencies]
glam = "0.33.2" # Vector math
chrono = "0.4.45" # Time
vulkano = "0.35.2" # Surface rendering
vulkano-shaders = "0.35.0" # Shadersssss
raw-window-handle = "0.6.2" # Huh
sdl3 = { version = "0", features = ["raw-window-handle"] } # Window & Input
bevy_ecs = "0.19.0" # ECS
rapier3d-f64 = { version = "0.35.3", features = ["parallel"] } # Physics engine
mimalloc = { version = "*", features = ["secure"] } # Smart memory
dirs = "6.0.0" # Useful dir paths
smallvec = "1.16.1" # Small vecs I guess
netcorehost = "0.22.0" # C# scripting
egui = "0.36.2" # UI
egui_winit_vulkano = "0.28.0" # UI in Vulkano
MathUtils = "1.0.1" # Math library
